CREATE TABLE [dbo].[Like]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[PostId] INT NOT NULL,
	[UserId] INT NOT NULL

	CONSTRAINT [PK_Like] PRIMARY KEY (Id)
	, CONSTRAINT FK_Like_Post FOREIGN KEY ([PostId]) REFERENCES Post (Id)
	, CONSTRAINT FK_Like_User FOREIGN KEY ([UserId]) REFERENCES [User] (Id)

)
