CREATE TABLE [dbo].[Tag]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[PostId] INT NOT NULL,
	[TagId] INT NOT NULL,
	[UserId] INT NOT NULL,
	[CreationDate] DATETIME NOT NULL CONSTRAINT DF_Tag_CreationDate DEFAULT GETDATE()

	CONSTRAINT [PK_Tag] PRIMARY KEY (Id)
	, CONSTRAINT FK_Tag_PostId FOREIGN KEY ([PostId]) REFERENCES Post (Id)
	, CONSTRAINT FK_Tag_UserId FOREIGN KEY ([UserId]) REFERENCES [User] (Id)
	, CONSTRAINT FK_Tag_TagId FOREIGN KEY ([TagId]) REFERENCES [TagLU] (Id)


	
)
