CREATE TABLE [dbo].[User]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
    [Name] VARCHAR(100) NOT NULL,
    [Email] VARCHAR(255) NOT NULL,
	[Role] VARCHAR(10) NOT NULL,
	[PasswordHash] VARBINARY(64) NOT NULL,
	[Salt] UNIQUEIDENTIFIER NOT NULL

	CONSTRAINT [PK_User] PRIMARY KEY (Id)
)
